### ISSUE TITLE
No border in Chromium menus

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nomad-gtk-themes#1]
Using Chromium 59 the menus don't have a border around them and they get visually lost with the background.

Using GTK 3.22

![](http://i.imgur.com/tFlimPP.png)
![](http://i.imgur.com/Jc4rAGc.png)

**Comment by luis-lavaire** [comment]
@UriHerrera which version of Gtk does it use? Also check your composition manager configuration.

**Comment by luis-lavaire** [comment]
Problem solved on [this commit](https://github.com/Nitrux/nomad-gtk-themes/commit/2e2693043b3cce847bb2858df97f9b1d339549f3).
