### ISSUE TITLE
Match dark gtk theme to dark Kvantum theme

### ISSUE THREAD

**Issue by UriHerrera** [Nitrux/nomad-gtk-themes#2]
![](https://i.imgur.com/Nw3Uwhb.png)

**Comment by luis-lavaire** [comment]
@UriHerrera I'm working on it. :smiley:.

**Comment by UriHerrera** [comment]
Headerbar/toolbar:
 ![#2b2c31](https://placehold.it/15/2b2c31/000000?text=+) `#2b2c31`

Window:
 ![#4e5456](https://placehold.it/15/4e5456/000000?text=+) `#4e5456`

Highlight:
 ![#26C6DA](https://placehold.it/15/26C6DA/000000?text=+) `#26C6DA`

Text:
 ![#f5f5f5](https://placehold.it/15/f5f5f5/000000?text=+) `#f5f5f5`

Tabs/Buttons/Checkboxes:
 ![#3a3f41](https://placehold.it/15/3a3f41/000000?text=+) `#3a3f41`

Borders:
 ![#61686b](https://placehold.it/15/61686b/000000?text=+) `#61686b`

**Comment by luis-lavaire** [comment]
Closing this with commit 437c48f.
